package hello.controller.news;

import hello.repository.news.YandexNews;
import hello.repository.news.YandexNewsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/news") // This means URL's start with /demo (after Application path)
public class YandexNewsController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private YandexNewsRepository yandexNewsRepository;

	@GetMapping(path="/all")
	public @ResponseBody
	Iterable<YandexNews> getAllUsers() {
		// This returns a JSON or XML with the users
		return yandexNewsRepository.findAll();
	}
}