package com.ione88.myServer.controller;

import com.ione88.myServer.entity.DnsProduct;
import com.ione88.myServer.repository.DnsProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller

@RequestMapping(path="/product") // This means URL's start with /demo (after Application path)
public class DnsProductController {
				// This means to get the bean called userRepository
	@Autowired	// Which is auto-generated by Spring, we will use it to handle the data
	private DnsProductRepository dnsProductRepository;
	//private UserService userService;

	@PostMapping(path="/add", consumes = "application/json", produces = "text/plain") // Map ONLY POST Requests
	public @ResponseBody String createDnsProduct (@RequestBody DnsProduct dnsProduct) {
		DnsProduct dnsProductPersist = dnsProductRepository.findByCode(dnsProduct.getCode());
		if (dnsProductPersist == null) {
			dnsProductRepository.save(dnsProduct);
			return "Saved";
		}
		dnsProduct.setDescription(dnsProduct.getDescription());
		dnsProduct.setName(dnsProduct.getName());
		dnsProduct.setParametrsJson(dnsProduct.getParametrsJson());
		dnsProduct.setPrice(dnsProduct.getPrice());
		dnsProduct.setUrl(dnsProduct.getUrl());
		dnsProductRepository.save(dnsProduct);
		return "Update";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<DnsProduct> getAllDnsProduct() {
		// This returns a JSON or XML with the users

		return dnsProductRepository.findAll();

	}
}
